Add "distcheck" step
A "distcheck" step is added as the last step, trying to install the
resulting source distribution. This helps catch common errors such as
forgetting to list files in `extra-source-files` or `other-modules`
which then aren't included in the resulting source distribution tarball.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -79,4 +79,14 @@ script:
  # tests that a source-distribution can be generated
  - cabal-1.18 sdist
 
+ # check that the generated source-distribution can be built & installed
+ - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal-1.18 install "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
+
 # EOF
